export const distrito = ["Mariano Melgar", "Miraflores", "Hunter", "Characato"];
export const banioPrivado = ["si", "no"];
export const tipoCasa = ["departamento", "habitacion", "casa"];
export const Casas = [
  {
    id: "001",
    descripcion:
      "ALQUILO AMPLIO Y CENTRICO DPTO EN AV.MANUEL CIPRIANO DULANTO (EX-AV.LA MAR) EN PUEBO LIBRE /3 HABITACIONES /CUARTO Y BAÑO DE SERVICIO .SUPER CENTRICO! A DOS CUADRAS DE PLAZA SAN MIGUEL Y LA PUCP- COLEGIOS -BANCOS -SUPERMERCADOS- CLINICAS Y VÍAS PRINCIPALES. DESCRIPCIÓN: -HABITACIÓN PRINCIPAL AMPLIA MUY ILUMINADA Y VENTILADA CON PISO TAPIZADO, WALKING CLOSET Y BAÑO COMPLETO INCORPORADO.. -LAS DOS HABITACIONES SECUNDARIAS COMPARTEN BAÑO CON EL BAÑO COMPLETO DE VISITA CADA HABITACIONES TIENE CLOSET DE PARED A PARED Y BELLO PISO TAPIZADO, -AMPLIA SALA COMEDOR CON BALCÓN VISTA A CALLE ,MUY ILUMINADO Y VENTILADO , PISO LAMINADO Y PARA PROTEGER TU INTIMIDAD LAS VENTANAS Y MAMPARA CUENTAN CON FINOS STORES DÁNDOLE UN TOQUE DE ELEGANCIA A TU NUEVO HOGAR, -ÁREA DE ESTUDIO CON MUEBLES ALTOS PARA QUE PUEDAS GUARDAR ARCHIVOS Y DEMÁS IDEAL PARA TRABAJAR O ESTUDIAR. -COCINA AMPLIA CON MUEBLES ALTOS Y BAJOS ,CAMPANA EXTRACTORA, CÓMODA Y AMPLIA. -AREA DE LAVANDERIA SEPARADA CON TENDAL Y CALENTADOR DE PASO DE 10 LITROS DE MARCA BOSCH. -AMPLIO CUARTO DE SERVICIO CON MUEBLES ALTOS PARA MAYOR COMODIDAD Y BAÑO DE SERVICIO COMPLETO, PUEDE SER USADA COMO UNA 4TA HABITACIÓN. AREAS COMUNES : -SALON DE NIÑOS. -SALON DE CINE. -SALÓN DE USO MÚLTIPLE. -SALON DE COMPUTO. -PISCINA . -GYM. -JUEGO PARA NIÑOS. -PARQUE INTERNO. -2 ASCENSORES. -LAVANDERÍA SOLO PARA RESIDENTES. -VIDEOVIGILANCIA PISO A PISO. -PORTERÍA Y VIGILANCIA 24X7. CONDICIONES: -MODALIDAD 2X1 . (1 MES DE ADELANTO Y 2 MESES DE GARANTIA) -CONTRATO POR UN AÑO -NO MASCOTAS . -MANTENIMIENTO S/.200 APROXIMADOS INCLUYE (AGUA -ALUMBRADO DE ÁREAS COMUNES-LIMPIEZA Y PORTERÍA VIGILANCIA.) -------------------------------------------9+2+2+5+0+2+6+4+3---------AGENDE VISITA-----------------------------------------",
    distrito: "Mariano Melgar",
    ciudad: "Arequipa",
    tamanio: "400 m2",
    banioPrivado: "si",
    tipoCasa: "departamento",
    precio: "450",
    amoblado: "no",
    ncuartos: "2"
  },
  {
    id: "002",
    descripcion:
      "ALQUILO AMPLIO Y CENTRICO DPTO EN AV.MANUEL CIPRIANO DULANTO (EX-AV.LA MAR) EN PUEBO LIBRE /3 HABITACIONES /CUARTO Y BAÑO DE SERVICIO .SUPER CENTRICO! A DOS CUADRAS DE PLAZA SAN MIGUEL Y LA PUCP- COLEGIOS -BANCOS -SUPERMERCADOS- CLINICAS Y VÍAS PRINCIPALES. DESCRIPCIÓN: -HABITACIÓN PRINCIPAL AMPLIA MUY ILUMINADA Y VENTILADA CON PISO TAPIZADO, WALKING CLOSET Y BAÑO COMPLETO INCORPORADO.. -LAS DOS HABITACIONES SECUNDARIAS COMPARTEN BAÑO CON EL BAÑO COMPLETO DE VISITA CADA HABITACIONES TIENE CLOSET DE PARED A PARED Y BELLO PISO TAPIZADO, -AMPLIA SALA COMEDOR CON BALCÓN VISTA A CALLE ,MUY ILUMINADO Y VENTILADO , PISO LAMINADO Y PARA PROTEGER TU INTIMIDAD LAS VENTANAS Y MAMPARA CUENTAN CON FINOS STORES DÁNDOLE UN TOQUE DE ELEGANCIA A TU NUEVO HOGAR, -ÁREA DE ESTUDIO CON MUEBLES ALTOS PARA QUE PUEDAS GUARDAR ARCHIVOS Y DEMÁS IDEAL PARA TRABAJAR O ESTUDIAR. -COCINA AMPLIA CON MUEBLES ALTOS Y BAJOS ,CAMPANA EXTRACTORA, CÓMODA Y AMPLIA. -AREA DE LAVANDERIA SEPARADA CON TENDAL Y CALENTADOR DE PASO DE 10 LITROS DE MARCA BOSCH. -AMPLIO CUARTO DE SERVICIO CON MUEBLES ALTOS PARA MAYOR COMODIDAD Y BAÑO DE SERVICIO COMPLETO, PUEDE SER USADA COMO UNA 4TA HABITACIÓN. AREAS COMUNES : -SALON DE NIÑOS. -SALON DE CINE. -SALÓN DE USO MÚLTIPLE. -SALON DE COMPUTO. -PISCINA . -GYM. -JUEGO PARA NIÑOS. -PARQUE INTERNO. -2 ASCENSORES. -LAVANDERÍA SOLO PARA RESIDENTES. -VIDEOVIGILANCIA PISO A PISO. -PORTERÍA Y VIGILANCIA 24X7. CONDICIONES: -MODALIDAD 2X1 . (1 MES DE ADELANTO Y 2 MESES DE GARANTIA) -CONTRATO POR UN AÑO -NO MASCOTAS . -MANTENIMIENTO S/.200 APROXIMADOS INCLUYE (AGUA -ALUMBRADO DE ÁREAS COMUNES-LIMPIEZA Y PORTERÍA VIGILANCIA.) -------------------------------------------9+2+2+5+0+2+6+4+3---------AGENDE VISITA-----------------------------------------",
    distrito: "Miraflores",
    ciudad: "Arequipa",
    tamanio: "300 m2",
    banioPrivado: "no",
    tipoCasa: "habitacion",
    precio: "850",
    amoblado: "si",
    ncuartos: "4"
  },
  {
    id: "003",
    descripcion:
      "ALQUILO AMPLIO Y CENTRICO DPTO EN AV.MANUEL CIPRIANO DULANTO (EX-AV.LA MAR) EN PUEBO LIBRE /3 HABITACIONES /CUARTO Y BAÑO DE SERVICIO .SUPER CENTRICO! A DOS CUADRAS DE PLAZA SAN MIGUEL Y LA PUCP- COLEGIOS -BANCOS -SUPERMERCADOS- CLINICAS Y VÍAS PRINCIPALES. DESCRIPCIÓN: -HABITACIÓN PRINCIPAL AMPLIA MUY ILUMINADA Y VENTILADA CON PISO TAPIZADO, WALKING CLOSET Y BAÑO COMPLETO INCORPORADO.. -LAS DOS HABITACIONES SECUNDARIAS COMPARTEN BAÑO CON EL BAÑO COMPLETO DE VISITA CADA HABITACIONES TIENE CLOSET DE PARED A PARED Y BELLO PISO TAPIZADO, -AMPLIA SALA COMEDOR CON BALCÓN VISTA A CALLE ,MUY ILUMINADO Y VENTILADO , PISO LAMINADO Y PARA PROTEGER TU INTIMIDAD LAS VENTANAS Y MAMPARA CUENTAN CON FINOS STORES DÁNDOLE UN TOQUE DE ELEGANCIA A TU NUEVO HOGAR, -ÁREA DE ESTUDIO CON MUEBLES ALTOS PARA QUE PUEDAS GUARDAR ARCHIVOS Y DEMÁS IDEAL PARA TRABAJAR O ESTUDIAR. -COCINA AMPLIA CON MUEBLES ALTOS Y BAJOS ,CAMPANA EXTRACTORA, CÓMODA Y AMPLIA. -AREA DE LAVANDERIA SEPARADA CON TENDAL Y CALENTADOR DE PASO DE 10 LITROS DE MARCA BOSCH. -AMPLIO CUARTO DE SERVICIO CON MUEBLES ALTOS PARA MAYOR COMODIDAD Y BAÑO DE SERVICIO COMPLETO, PUEDE SER USADA COMO UNA 4TA HABITACIÓN. AREAS COMUNES : -SALON DE NIÑOS. -SALON DE CINE. -SALÓN DE USO MÚLTIPLE. -SALON DE COMPUTO. -PISCINA . -GYM. -JUEGO PARA NIÑOS. -PARQUE INTERNO. -2 ASCENSORES. -LAVANDERÍA SOLO PARA RESIDENTES. -VIDEOVIGILANCIA PISO A PISO. -PORTERÍA Y VIGILANCIA 24X7. CONDICIONES: -MODALIDAD 2X1 . (1 MES DE ADELANTO Y 2 MESES DE GARANTIA) -CONTRATO POR UN AÑO -NO MASCOTAS . -MANTENIMIENTO S/.200 APROXIMADOS INCLUYE (AGUA -ALUMBRADO DE ÁREAS COMUNES-LIMPIEZA Y PORTERÍA VIGILANCIA.) -------------------------------------------9+2+2+5+0+2+6+4+3---------AGENDE VISITA-----------------------------------------",
    distrito: "Socabaya",
    ciudad: "Arequipa",
    tamanio: "670 m2",
    banioPrivado: "no",
    tipoCasa: "casa",
    precio: "1050",
    amoblado: "si",
    ncuartos: "5"
  },
  {
    id: "004",
    descripcion:
      "ALQUILO AMPLIO Y CENTRICO DPTO EN AV.MANUEL CIPRIANO DULANTO (EX-AV.LA MAR) EN PUEBO LIBRE /3 HABITACIONES /CUARTO Y BAÑO DE SERVICIO .SUPER CENTRICO! A DOS CUADRAS DE PLAZA SAN MIGUEL Y LA PUCP- COLEGIOS -BANCOS -SUPERMERCADOS- CLINICAS Y VÍAS PRINCIPALES. DESCRIPCIÓN: -HABITACIÓN PRINCIPAL AMPLIA MUY ILUMINADA Y VENTILADA CON PISO TAPIZADO, WALKING CLOSET Y BAÑO COMPLETO INCORPORADO.. -LAS DOS HABITACIONES SECUNDARIAS COMPARTEN BAÑO CON EL BAÑO COMPLETO DE VISITA CADA HABITACIONES TIENE CLOSET DE PARED A PARED Y BELLO PISO TAPIZADO, -AMPLIA SALA COMEDOR CON BALCÓN VISTA A CALLE ,MUY ILUMINADO Y VENTILADO , PISO LAMINADO Y PARA PROTEGER TU INTIMIDAD LAS VENTANAS Y MAMPARA CUENTAN CON FINOS STORES DÁNDOLE UN TOQUE DE ELEGANCIA A TU NUEVO HOGAR, -ÁREA DE ESTUDIO CON MUEBLES ALTOS PARA QUE PUEDAS GUARDAR ARCHIVOS Y DEMÁS IDEAL PARA TRABAJAR O ESTUDIAR. -COCINA AMPLIA CON MUEBLES ALTOS Y BAJOS ,CAMPANA EXTRACTORA, CÓMODA Y AMPLIA. -AREA DE LAVANDERIA SEPARADA CON TENDAL Y CALENTADOR DE PASO DE 10 LITROS DE MARCA BOSCH. -AMPLIO CUARTO DE SERVICIO CON MUEBLES ALTOS PARA MAYOR COMODIDAD Y BAÑO DE SERVICIO COMPLETO, PUEDE SER USADA COMO UNA 4TA HABITACIÓN. AREAS COMUNES : -SALON DE NIÑOS. -SALON DE CINE. -SALÓN DE USO MÚLTIPLE. -SALON DE COMPUTO. -PISCINA . -GYM. -JUEGO PARA NIÑOS. -PARQUE INTERNO. -2 ASCENSORES. -LAVANDERÍA SOLO PARA RESIDENTES. -VIDEOVIGILANCIA PISO A PISO. -PORTERÍA Y VIGILANCIA 24X7. CONDICIONES: -MODALIDAD 2X1 . (1 MES DE ADELANTO Y 2 MESES DE GARANTIA) -CONTRATO POR UN AÑO -NO MASCOTAS . -MANTENIMIENTO S/.200 APROXIMADOS INCLUYE (AGUA -ALUMBRADO DE ÁREAS COMUNES-LIMPIEZA Y PORTERÍA VIGILANCIA.) -------------------------------------------9+2+2+5+0+2+6+4+3---------AGENDE VISITA-----------------------------------------",
    distrito: "Hunter",
    ciudad: "Arequipa",
    tamanio: "780 m2",
    banioPrivado: "no",
    tipoCasa: "habitacion",
    precio: "650",
    amoblado: "no",
    ncuartos: "4"
  },
  {
    id: "005",
    descripcion:
      "ALQUILO AMPLIO Y CENTRICO DPTO EN AV.MANUEL CIPRIANO DULANTO (EX-AV.LA MAR) EN PUEBO LIBRE /3 HABITACIONES /CUARTO Y BAÑO DE SERVICIO .SUPER CENTRICO! A DOS CUADRAS DE PLAZA SAN MIGUEL Y LA PUCP- COLEGIOS -BANCOS -SUPERMERCADOS- CLINICAS Y VÍAS PRINCIPALES. DESCRIPCIÓN: -HABITACIÓN PRINCIPAL AMPLIA MUY ILUMINADA Y VENTILADA CON PISO TAPIZADO, WALKING CLOSET Y BAÑO COMPLETO INCORPORADO.. -LAS DOS HABITACIONES SECUNDARIAS COMPARTEN BAÑO CON EL BAÑO COMPLETO DE VISITA CADA HABITACIONES TIENE CLOSET DE PARED A PARED Y BELLO PISO TAPIZADO, -AMPLIA SALA COMEDOR CON BALCÓN VISTA A CALLE ,MUY ILUMINADO Y VENTILADO , PISO LAMINADO Y PARA PROTEGER TU INTIMIDAD LAS VENTANAS Y MAMPARA CUENTAN CON FINOS STORES DÁNDOLE UN TOQUE DE ELEGANCIA A TU NUEVO HOGAR, -ÁREA DE ESTUDIO CON MUEBLES ALTOS PARA QUE PUEDAS GUARDAR ARCHIVOS Y DEMÁS IDEAL PARA TRABAJAR O ESTUDIAR. -COCINA AMPLIA CON MUEBLES ALTOS Y BAJOS ,CAMPANA EXTRACTORA, CÓMODA Y AMPLIA. -AREA DE LAVANDERIA SEPARADA CON TENDAL Y CALENTADOR DE PASO DE 10 LITROS DE MARCA BOSCH. -AMPLIO CUARTO DE SERVICIO CON MUEBLES ALTOS PARA MAYOR COMODIDAD Y BAÑO DE SERVICIO COMPLETO, PUEDE SER USADA COMO UNA 4TA HABITACIÓN. AREAS COMUNES : -SALON DE NIÑOS. -SALON DE CINE. -SALÓN DE USO MÚLTIPLE. -SALON DE COMPUTO. -PISCINA . -GYM. -JUEGO PARA NIÑOS. -PARQUE INTERNO. -2 ASCENSORES. -LAVANDERÍA SOLO PARA RESIDENTES. -VIDEOVIGILANCIA PISO A PISO. -PORTERÍA Y VIGILANCIA 24X7. CONDICIONES: -MODALIDAD 2X1 . (1 MES DE ADELANTO Y 2 MESES DE GARANTIA) -CONTRATO POR UN AÑO -NO MASCOTAS . -MANTENIMIENTO S/.200 APROXIMADOS INCLUYE (AGUA -ALUMBRADO DE ÁREAS COMUNES-LIMPIEZA Y PORTERÍA VIGILANCIA.) -------------------------------------------9+2+2+5+0+2+6+4+3---------AGENDE VISITA-----------------------------------------",
    distrito: "Characato",
    ciudad: "Arequipa",
    tamanio: "500 m2",
    banioPrivado: "no",
    tipoCasa: "departamento",
    precio: "350",
    amoblado: "no",
    ncuartos: "3"
  },
  {
    id: "006",
    descripcion:
      "ALQUILO AMPLIO Y CENTRICO DPTO EN AV.MANUEL CIPRIANO DULANTO (EX-AV.LA MAR) EN PUEBO LIBRE /3 HABITACIONES /CUARTO Y BAÑO DE SERVICIO .SUPER CENTRICO! A DOS CUADRAS DE PLAZA SAN MIGUEL Y LA PUCP- COLEGIOS -BANCOS -SUPERMERCADOS- CLINICAS Y VÍAS PRINCIPALES. DESCRIPCIÓN: -HABITACIÓN PRINCIPAL AMPLIA MUY ILUMINADA Y VENTILADA CON PISO TAPIZADO, WALKING CLOSET Y BAÑO COMPLETO INCORPORADO.. -LAS DOS HABITACIONES SECUNDARIAS COMPARTEN BAÑO CON EL BAÑO COMPLETO DE VISITA CADA HABITACIONES TIENE CLOSET DE PARED A PARED Y BELLO PISO TAPIZADO, -AMPLIA SALA COMEDOR CON BALCÓN VISTA A CALLE ,MUY ILUMINADO Y VENTILADO , PISO LAMINADO Y PARA PROTEGER TU INTIMIDAD LAS VENTANAS Y MAMPARA CUENTAN CON FINOS STORES DÁNDOLE UN TOQUE DE ELEGANCIA A TU NUEVO HOGAR, -ÁREA DE ESTUDIO CON MUEBLES ALTOS PARA QUE PUEDAS GUARDAR ARCHIVOS Y DEMÁS IDEAL PARA TRABAJAR O ESTUDIAR. -COCINA AMPLIA CON MUEBLES ALTOS Y BAJOS ,CAMPANA EXTRACTORA, CÓMODA Y AMPLIA. -AREA DE LAVANDERIA SEPARADA CON TENDAL Y CALENTADOR DE PASO DE 10 LITROS DE MARCA BOSCH. -AMPLIO CUARTO DE SERVICIO CON MUEBLES ALTOS PARA MAYOR COMODIDAD Y BAÑO DE SERVICIO COMPLETO, PUEDE SER USADA COMO UNA 4TA HABITACIÓN. AREAS COMUNES : -SALON DE NIÑOS. -SALON DE CINE. -SALÓN DE USO MÚLTIPLE. -SALON DE COMPUTO. -PISCINA . -GYM. -JUEGO PARA NIÑOS. -PARQUE INTERNO. -2 ASCENSORES. -LAVANDERÍA SOLO PARA RESIDENTES. -VIDEOVIGILANCIA PISO A PISO. -PORTERÍA Y VIGILANCIA 24X7. CONDICIONES: -MODALIDAD 2X1 . (1 MES DE ADELANTO Y 2 MESES DE GARANTIA) -CONTRATO POR UN AÑO -NO MASCOTAS . -MANTENIMIENTO S/.200 APROXIMADOS INCLUYE (AGUA -ALUMBRADO DE ÁREAS COMUNES-LIMPIEZA Y PORTERÍA VIGILANCIA.) -------------------------------------------9+2+2+5+0+2+6+4+3---------AGENDE VISITA-----------------------------------------",
    distrito: "Mariano Melgar",
    ciudad: "Arequipa",
    tamanio: "420 m2",
    banioPrivado: "si",
    tipoCasa: "casa",
    precio: "450",
    amoblado: "no",
    ncuartos: "5"
  },
  {
    id: "007",
    descripcion:
      "ALQUILO AMPLIO Y CENTRICO DPTO EN AV.MANUEL CIPRIANO DULANTO (EX-AV.LA MAR) EN PUEBO LIBRE /3 HABITACIONES /CUARTO Y BAÑO DE SERVICIO .SUPER CENTRICO! A DOS CUADRAS DE PLAZA SAN MIGUEL Y LA PUCP- COLEGIOS -BANCOS -SUPERMERCADOS- CLINICAS Y VÍAS PRINCIPALES. DESCRIPCIÓN: -HABITACIÓN PRINCIPAL AMPLIA MUY ILUMINADA Y VENTILADA CON PISO TAPIZADO, WALKING CLOSET Y BAÑO COMPLETO INCORPORADO.. -LAS DOS HABITACIONES SECUNDARIAS COMPARTEN BAÑO CON EL BAÑO COMPLETO DE VISITA CADA HABITACIONES TIENE CLOSET DE PARED A PARED Y BELLO PISO TAPIZADO, -AMPLIA SALA COMEDOR CON BALCÓN VISTA A CALLE ,MUY ILUMINADO Y VENTILADO , PISO LAMINADO Y PARA PROTEGER TU INTIMIDAD LAS VENTANAS Y MAMPARA CUENTAN CON FINOS STORES DÁNDOLE UN TOQUE DE ELEGANCIA A TU NUEVO HOGAR, -ÁREA DE ESTUDIO CON MUEBLES ALTOS PARA QUE PUEDAS GUARDAR ARCHIVOS Y DEMÁS IDEAL PARA TRABAJAR O ESTUDIAR. -COCINA AMPLIA CON MUEBLES ALTOS Y BAJOS ,CAMPANA EXTRACTORA, CÓMODA Y AMPLIA. -AREA DE LAVANDERIA SEPARADA CON TENDAL Y CALENTADOR DE PASO DE 10 LITROS DE MARCA BOSCH. -AMPLIO CUARTO DE SERVICIO CON MUEBLES ALTOS PARA MAYOR COMODIDAD Y BAÑO DE SERVICIO COMPLETO, PUEDE SER USADA COMO UNA 4TA HABITACIÓN. AREAS COMUNES : -SALON DE NIÑOS. -SALON DE CINE. -SALÓN DE USO MÚLTIPLE. -SALON DE COMPUTO. -PISCINA . -GYM. -JUEGO PARA NIÑOS. -PARQUE INTERNO. -2 ASCENSORES. -LAVANDERÍA SOLO PARA RESIDENTES. -VIDEOVIGILANCIA PISO A PISO. -PORTERÍA Y VIGILANCIA 24X7. CONDICIONES: -MODALIDAD 2X1 . (1 MES DE ADELANTO Y 2 MESES DE GARANTIA) -CONTRATO POR UN AÑO -NO MASCOTAS . -MANTENIMIENTO S/.200 APROXIMADOS INCLUYE (AGUA -ALUMBRADO DE ÁREAS COMUNES-LIMPIEZA Y PORTERÍA VIGILANCIA.) -------------------------------------------9+2+2+5+0+2+6+4+3---------AGENDE VISITA-----------------------------------------",
    distrito: "Miraflores",
    ciudad: "Arequipa",
    tamanio: "300 m2",
    banioPrivado: "no",
    tipoCasa: "habitacion",
    precio: "1250",
    amoblado: "no",
    ncuartos: "3"
  },
  {
    id: "008",
    descripcion:
      "ALQUILO AMPLIO Y CENTRICO DPTO EN AV.MANUEL CIPRIANO DULANTO (EX-AV.LA MAR) EN PUEBO LIBRE /3 HABITACIONES /CUARTO Y BAÑO DE SERVICIO .SUPER CENTRICO! A DOS CUADRAS DE PLAZA SAN MIGUEL Y LA PUCP- COLEGIOS -BANCOS -SUPERMERCADOS- CLINICAS Y VÍAS PRINCIPALES. DESCRIPCIÓN: -HABITACIÓN PRINCIPAL AMPLIA MUY ILUMINADA Y VENTILADA CON PISO TAPIZADO, WALKING CLOSET Y BAÑO COMPLETO INCORPORADO.. -LAS DOS HABITACIONES SECUNDARIAS COMPARTEN BAÑO CON EL BAÑO COMPLETO DE VISITA CADA HABITACIONES TIENE CLOSET DE PARED A PARED Y BELLO PISO TAPIZADO, -AMPLIA SALA COMEDOR CON BALCÓN VISTA A CALLE ,MUY ILUMINADO Y VENTILADO , PISO LAMINADO Y PARA PROTEGER TU INTIMIDAD LAS VENTANAS Y MAMPARA CUENTAN CON FINOS STORES DÁNDOLE UN TOQUE DE ELEGANCIA A TU NUEVO HOGAR, -ÁREA DE ESTUDIO CON MUEBLES ALTOS PARA QUE PUEDAS GUARDAR ARCHIVOS Y DEMÁS IDEAL PARA TRABAJAR O ESTUDIAR. -COCINA AMPLIA CON MUEBLES ALTOS Y BAJOS ,CAMPANA EXTRACTORA, CÓMODA Y AMPLIA. -AREA DE LAVANDERIA SEPARADA CON TENDAL Y CALENTADOR DE PASO DE 10 LITROS DE MARCA BOSCH. -AMPLIO CUARTO DE SERVICIO CON MUEBLES ALTOS PARA MAYOR COMODIDAD Y BAÑO DE SERVICIO COMPLETO, PUEDE SER USADA COMO UNA 4TA HABITACIÓN. AREAS COMUNES : -SALON DE NIÑOS. -SALON DE CINE. -SALÓN DE USO MÚLTIPLE. -SALON DE COMPUTO. -PISCINA . -GYM. -JUEGO PARA NIÑOS. -PARQUE INTERNO. -2 ASCENSORES. -LAVANDERÍA SOLO PARA RESIDENTES. -VIDEOVIGILANCIA PISO A PISO. -PORTERÍA Y VIGILANCIA 24X7. CONDICIONES: -MODALIDAD 2X1 . (1 MES DE ADELANTO Y 2 MESES DE GARANTIA) -CONTRATO POR UN AÑO -NO MASCOTAS . -MANTENIMIENTO S/.200 APROXIMADOS INCLUYE (AGUA -ALUMBRADO DE ÁREAS COMUNES-LIMPIEZA Y PORTERÍA VIGILANCIA.) -------------------------------------------9+2+2+5+0+2+6+4+3---------AGENDE VISITA-----------------------------------------",
    distrito: "Socabaya",
    ciudad: "Arequipa",
    tamanio: "680 m2",
    banioPrivado: "si",
    tipoCasa: "departamento",
    precio: "850",
    amoblado: "si",
    ncuartos: "6"
  },
  {
    id: "009",
    descripcion:
      "ALQUILO AMPLIO Y CENTRICO DPTO EN AV.MANUEL CIPRIANO DULANTO (EX-AV.LA MAR) EN PUEBO LIBRE /3 HABITACIONES /CUARTO Y BAÑO DE SERVICIO .SUPER CENTRICO! A DOS CUADRAS DE PLAZA SAN MIGUEL Y LA PUCP- COLEGIOS -BANCOS -SUPERMERCADOS- CLINICAS Y VÍAS PRINCIPALES. DESCRIPCIÓN: -HABITACIÓN PRINCIPAL AMPLIA MUY ILUMINADA Y VENTILADA CON PISO TAPIZADO, WALKING CLOSET Y BAÑO COMPLETO INCORPORADO.. -LAS DOS HABITACIONES SECUNDARIAS COMPARTEN BAÑO CON EL BAÑO COMPLETO DE VISITA CADA HABITACIONES TIENE CLOSET DE PARED A PARED Y BELLO PISO TAPIZADO, -AMPLIA SALA COMEDOR CON BALCÓN VISTA A CALLE ,MUY ILUMINADO Y VENTILADO , PISO LAMINADO Y PARA PROTEGER TU INTIMIDAD LAS VENTANAS Y MAMPARA CUENTAN CON FINOS STORES DÁNDOLE UN TOQUE DE ELEGANCIA A TU NUEVO HOGAR, -ÁREA DE ESTUDIO CON MUEBLES ALTOS PARA QUE PUEDAS GUARDAR ARCHIVOS Y DEMÁS IDEAL PARA TRABAJAR O ESTUDIAR. -COCINA AMPLIA CON MUEBLES ALTOS Y BAJOS ,CAMPANA EXTRACTORA, CÓMODA Y AMPLIA. -AREA DE LAVANDERIA SEPARADA CON TENDAL Y CALENTADOR DE PASO DE 10 LITROS DE MARCA BOSCH. -AMPLIO CUARTO DE SERVICIO CON MUEBLES ALTOS PARA MAYOR COMODIDAD Y BAÑO DE SERVICIO COMPLETO, PUEDE SER USADA COMO UNA 4TA HABITACIÓN. AREAS COMUNES : -SALON DE NIÑOS. -SALON DE CINE. -SALÓN DE USO MÚLTIPLE. -SALON DE COMPUTO. -PISCINA . -GYM. -JUEGO PARA NIÑOS. -PARQUE INTERNO. -2 ASCENSORES. -LAVANDERÍA SOLO PARA RESIDENTES. -VIDEOVIGILANCIA PISO A PISO. -PORTERÍA Y VIGILANCIA 24X7. CONDICIONES: -MODALIDAD 2X1 . (1 MES DE ADELANTO Y 2 MESES DE GARANTIA) -CONTRATO POR UN AÑO -NO MASCOTAS . -MANTENIMIENTO S/.200 APROXIMADOS INCLUYE (AGUA -ALUMBRADO DE ÁREAS COMUNES-LIMPIEZA Y PORTERÍA VIGILANCIA.) -------------------------------------------9+2+2+5+0+2+6+4+3---------AGENDE VISITA-----------------------------------------",
    distrito: "Hunter",
    ciudad: "Arequipa",
    tamanio: "780 m2",
    banioPrivado: "no",
    tipoCasa: "habitacion",
    precio: "750",
    amoblado: "no",
    ncuartos: "6"
  },
  {
    id: "010",
    descripcion:
      "ALQUILO AMPLIO Y CENTRICO DPTO EN AV.MANUEL CIPRIANO DULANTO (EX-AV.LA MAR) EN PUEBO LIBRE /3 HABITACIONES /CUARTO Y BAÑO DE SERVICIO .SUPER CENTRICO! A DOS CUADRAS DE PLAZA SAN MIGUEL Y LA PUCP- COLEGIOS -BANCOS -SUPERMERCADOS- CLINICAS Y VÍAS PRINCIPALES. DESCRIPCIÓN: -HABITACIÓN PRINCIPAL AMPLIA MUY ILUMINADA Y VENTILADA CON PISO TAPIZADO, WALKING CLOSET Y BAÑO COMPLETO INCORPORADO.. -LAS DOS HABITACIONES SECUNDARIAS COMPARTEN BAÑO CON EL BAÑO COMPLETO DE VISITA CADA HABITACIONES TIENE CLOSET DE PARED A PARED Y BELLO PISO TAPIZADO, -AMPLIA SALA COMEDOR CON BALCÓN VISTA A CALLE ,MUY ILUMINADO Y VENTILADO , PISO LAMINADO Y PARA PROTEGER TU INTIMIDAD LAS VENTANAS Y MAMPARA CUENTAN CON FINOS STORES DÁNDOLE UN TOQUE DE ELEGANCIA A TU NUEVO HOGAR, -ÁREA DE ESTUDIO CON MUEBLES ALTOS PARA QUE PUEDAS GUARDAR ARCHIVOS Y DEMÁS IDEAL PARA TRABAJAR O ESTUDIAR. -COCINA AMPLIA CON MUEBLES ALTOS Y BAJOS ,CAMPANA EXTRACTORA, CÓMODA Y AMPLIA. -AREA DE LAVANDERIA SEPARADA CON TENDAL Y CALENTADOR DE PASO DE 10 LITROS DE MARCA BOSCH. -AMPLIO CUARTO DE SERVICIO CON MUEBLES ALTOS PARA MAYOR COMODIDAD Y BAÑO DE SERVICIO COMPLETO, PUEDE SER USADA COMO UNA 4TA HABITACIÓN. AREAS COMUNES : -SALON DE NIÑOS. -SALON DE CINE. -SALÓN DE USO MÚLTIPLE. -SALON DE COMPUTO. -PISCINA . -GYM. -JUEGO PARA NIÑOS. -PARQUE INTERNO. -2 ASCENSORES. -LAVANDERÍA SOLO PARA RESIDENTES. -VIDEOVIGILANCIA PISO A PISO. -PORTERÍA Y VIGILANCIA 24X7. CONDICIONES: -MODALIDAD 2X1 . (1 MES DE ADELANTO Y 2 MESES DE GARANTIA) -CONTRATO POR UN AÑO -NO MASCOTAS . -MANTENIMIENTO S/.200 APROXIMADOS INCLUYE (AGUA -ALUMBRADO DE ÁREAS COMUNES-LIMPIEZA Y PORTERÍA VIGILANCIA.) -------------------------------------------9+2+2+5+0+2+6+4+3---------AGENDE VISITA-----------------------------------------",
    distrito: "Characato",
    ciudad: "Arequipa",
    tamanio: "500 m2",
    banioPrivado: "si",
    tipoCasa: "casa",
    precio: "250",
    amoblado: "si",
    ncuartos: "4"
  }
];
